#!/usr/bin/env python3
"""Writes src/include/png_tests.inc: small PNGs covering the decoder's formats
(RGBA8 + all five filters + dynamic Huffman, RGB8 stored + tRNS key,
4-bit palette + tRNS, 2-bit grey, 16-bit grey+alpha) with the FNV-1a hash
of the RGBA8 pixels the decoder must produce. Run after changing it:
    python3 tools/make_png_tests.py
"""
import os, struct, zlib

def chunk(t, d):
    return struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)

def png(w, h, depth, ctype, rows, level, plte=None, trns=None):
    bpp = max(1, ({0: 1, 2: 3, 3: 1, 4: 2, 6: 4}[ctype] * depth) // 8)
    raw = b""
    prev = bytes(len(rows[0]))
    for y, row in enumerate(rows):
        f = y % 5
        out = bytearray()
        for i, x in enumerate(row):
            a = row[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 0: p = 0
            elif f == 1: p = a
            elif f == 2: p = b
            elif f == 3: p = (a + b) // 2
            else:
                pp = a + b - c; pa, pb, pc = abs(pp - a), abs(pp - b), abs(pp - c)
                p = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
            out.append((x - p) & 255)
        raw += bytes([f]) + bytes(out)
        prev = row
    data = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, depth, ctype, 0, 0, 0))
    if plte: data += chunk(b"PLTE", plte)
    if trns is not None: data += chunk(b"tRNS", trns)
    z = zlib.compress(raw, level)
    data += chunk(b"IDAT", z[:len(z) // 2]) + chunk(b"IDAT", z[len(z) // 2:])   # split IDAT
    return data + chunk(b"IEND", b"")

def fnv(b):
    h = 0x811c9dc5
    for x in b:
        h = ((h ^ x) * 0x01000193) & 0xffffffff
    return h

tests = []
# 1: RGBA8 32x32 patterns, level 9
w = h = 32
rows, rgba = [], b""
for y in range(h):
    r = bytes(v for x in range(w) for v in ((x * 7 + y * 3) & 255, (x * x + y) & 255, (y * 11) & 255, (255 - x * 5) & 255))
    rows.append(r); rgba += r
tests.append((png(w, h, 8, 6, rows, 9), w, h, rgba))
# 2: RGB8 9x7 stored, tRNS key (10, 20, 30)
w, h = 9, 7
rows, rgba = [], b""
for y in range(h):
    px = [(10, 20, 30) if (x + y) % 4 == 0 else ((x * 29) & 255, (y * 31) & 255, (x * y * 3) & 255) for x in range(w)]
    rows.append(bytes(v for p in px for v in p))
    rgba += bytes(v for p in px for v in (p + ((0,) if p == (10, 20, 30) else (255,))))
tests.append((png(w, h, 8, 2, rows, 0, trns=struct.pack(">HHH", 10, 20, 30)), w, h, rgba))
# 3: palette 4-bit 13x5 with tRNS
w, h = 13, 5
pal = [((i * 37) & 255, (i * 73) & 255, (i * 101) & 255) for i in range(16)]
alpha = bytes([0, 128, 255, 64])
rows, rgba = [], b""
for y in range(h):
    idx = [(x * 3 + y * 5) % 16 for x in range(w)]
    packed = bytearray()
    for i in range(0, w, 2):
        hi = idx[i]; lo = idx[i + 1] if i + 1 < w else 0
        packed.append(hi << 4 | lo)
    rows.append(bytes(packed))
    rgba += bytes(v for i in idx for v in (pal[i] + ((alpha[i] if i < len(alpha) else 255),)))
tests.append((png(w, h, 4, 3, rows, 1, plte=bytes(v for p in pal for v in p), trns=alpha), w, h, rgba))
# 4: grey 2-bit 11x3
w, h = 11, 3
rows, rgba = [], b""
for y in range(h):
    vals = [(x + y) % 4 for x in range(w)]
    packed = bytearray()
    for i in range(0, w, 4):
        b = 0
        for k in range(4):
            b = (b << 2) | (vals[i + k] if i + k < w else 0)
        packed.append(b)
    rows.append(bytes(packed))
    rgba += bytes(v for g in vals for v in (g * 255 // 3,) * 3 + (255,))
tests.append((png(w, h, 2, 0, rows, 6), w, h, rgba))
# 5: grey+alpha 16-bit 5x4
w, h = 5, 4
rows, rgba = [], b""
for y in range(h):
    px = [((x * 9000 + y * 300) & 0xffff, (65535 - x * 7000) & 0xffff) for x in range(w)]
    rows.append(b"".join(struct.pack(">HH", g, a) for g, a in px))
    rgba += bytes(v for g, a in px for v in (g >> 8, g >> 8, g >> 8, a >> 8))
tests.append((png(w, h, 16, 4, rows, 6), w, h, rgba))

out = os.path.join(os.path.dirname(__file__), "..", "src", "include", "png_tests.inc")
with open(out, "w") as f:
    f.write("; Generated by tools/make_png_tests.py: test PNGs for the self test.\n")
    f.write("; Each entry: dq data, size; dd width, height, fnv1a(rgba8).\n")
    f.write("%%define PNG_TEST_COUNT %d\n" % len(tests))
    f.write("section .rdata\nalign 8\npng_tests:\n")
    for i, (data, w, h, rgba) in enumerate(tests):
        f.write("    dq png_t%d, %d\n    dd %d, %d, 0x%08x, 0\n" % (i, len(data), w, h, fnv(rgba)))
    for i, (data, w, h, rgba) in enumerate(tests):
        f.write("png_t%d:\n" % i)
        for k in range(0, len(data), 16):
            f.write("    db " + ", ".join("0x%02x" % b for b in data[k:k + 16]) + "\n")
print("wrote", os.path.normpath(out), len(tests), "tests")
